#define SHERLOC_MAJOR_VERSION  "0"
#define SHERLOC_MINOR_VERSION  "1"
#define SHERLOC_MICRO_VERSION  "1"

#define SHERLOC_VERSION_STR(major, minor, micro) "v" major "." minor "." micro
#define SHERLOC_VERSION SHERLOC_VERSION_STR(SHERLOC_MAJOR_VERSION, SHERLOC_MINOR_VERSION, SHERLOC_MICRO_VERSION)